export const animalActionType = {
  GET_ANIMALS: "GET_ANIMALS",
  ANIMAL_ERROR: "ANIMAL_ERROR",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAIL: "POST_FAIL",
  POST_DELETE: "POST_DELETE",
  POST_ERROR: "POST_ERROR",
  SINGLE_ANM: "SINGLE_ANM",
  SINGLE_ERROR: "SINGLE_ERROR",
  POST_UPDATE:"POST_UPDATE",
  UPDATE_ERROR:"UPDATE_ERROR",
};
